# Generated by Django 4.2.26 on 2025-11-12 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_semester_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='drop_lowest',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='course',
            name='is_pass_fail',
            field=models.BooleanField(default=False),
        ),
    ]
