# Generated by Django 4.2.26 on 2025-11-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_assignment_drop_lowest_course_is_pass_fail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=3),
        ),
    ]
