# Generated by Django 4.2.27 on 2026-01-14 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0007_course_percent_boost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradescale',
            name='gpa_value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4.33)]),
        ),
    ]
