-- Durable cloud state for ordering, course grading configuration, user state,
-- and recoverable one-time imports from legacy browser storage.

alter table if exists public.semesters
  add column if not exists sort_order integer;

do $$
begin
  if to_regclass('public.semesters') is not null then
    with ranked as (
      select id, row_number() over (partition by user_id order by created_at, id) - 1 as position
      from public.semesters
    )
    update public.semesters as semesters
    set sort_order = ranked.position
    from ranked
    where semesters.id = ranked.id and semesters.sort_order is null;
  end if;
end $$;

alter table if exists public.semesters
  alter column sort_order set default 0,
  alter column sort_order set not null;

alter table if exists public.courses
  add column if not exists sort_order integer,
  add column if not exists pass_label varchar(24),
  add column if not exists fail_label varchar(24),
  add column if not exists pass_threshold double precision,
  add column if not exists letter_grade_scale jsonb;

do $$
begin
  if to_regclass('public.courses') is not null then
    with ranked as (
      select id, row_number() over (partition by semester_id order by created_at, id) - 1 as position
      from public.courses
    )
    update public.courses as courses
    set sort_order = ranked.position
    from ranked
    where courses.id = ranked.id and courses.sort_order is null;
  end if;
end $$;

alter table if exists public.courses
  alter column sort_order set default 0,
  alter column sort_order set not null;

alter table if exists public.assignments
  add column if not exists client_id varchar(64),
  add column if not exists sort_order integer,
  add column if not exists extra_credit double precision,
  add column if not exists sub_items jsonb;

do $$
begin
  if to_regclass('public.assignments') is not null then
    update public.assignments
    set client_id = id::text
    where client_id is null;

    with ranked as (
      select id, row_number() over (partition by course_id order by created_at, id) - 1 as position
      from public.assignments
    )
    update public.assignments as assignments
    set sort_order = ranked.position
    from ranked
    where assignments.id = ranked.id and assignments.sort_order is null;
  end if;
end $$;

alter table if exists public.assignments
  alter column client_id set not null,
  alter column sort_order set default 0,
  alter column sort_order set not null;

alter table if exists public.user_settings
  add column if not exists dashboard_message varchar(240),
  add column if not exists last_active_semester_id integer,
  add column if not exists local_migration_version integer not null default 0;

create table if not exists public.legacy_local_backups (
  id bigint generated by default as identity primary key,
  user_id varchar(255) not null,
  scope_key varchar(255) not null,
  payload_json jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint legacy_local_backups_user_scope_unique unique (user_id, scope_key)
);

do $$
begin
  if to_regclass('public.semesters') is not null then
    create index if not exists ix_semesters_user_sort
      on public.semesters (user_id, sort_order, id);
  end if;
  if to_regclass('public.courses') is not null then
    create index if not exists ix_courses_semester_sort
      on public.courses (semester_id, sort_order, id);
  end if;
  if to_regclass('public.assignments') is not null then
    create index if not exists ix_assignments_course_sort
      on public.assignments (course_id, sort_order, id);
    create unique index if not exists ux_assignments_course_client_id
      on public.assignments (course_id, client_id);
  end if;
end $$;
create index if not exists ix_legacy_local_backups_user
  on public.legacy_local_backups (user_id);

do $$
begin
  if to_regclass('public.courses') is not null and not exists (
    select 1 from pg_constraint where conname = 'courses_pass_threshold_range'
  ) then
    alter table public.courses add constraint courses_pass_threshold_range
      check (pass_threshold is null or (pass_threshold >= 0 and pass_threshold <= 100));
  end if;
  if to_regclass('public.assignments') is not null and not exists (
    select 1 from pg_constraint where conname = 'assignments_extra_credit_range'
  ) then
    alter table public.assignments add constraint assignments_extra_credit_range
      check (extra_credit is null or (extra_credit >= 0 and extra_credit <= 100));
  end if;
  if to_regclass('public.assignments') is not null and not exists (
    select 1 from pg_constraint where conname = 'assignments_sub_items_array'
  ) then
    alter table public.assignments add constraint assignments_sub_items_array
      check (sub_items is null or jsonb_typeof(sub_items) = 'array');
  end if;
  if to_regclass('public.courses') is not null and not exists (
    select 1 from pg_constraint where conname = 'courses_letter_grade_scale_array'
  ) then
    alter table public.courses add constraint courses_letter_grade_scale_array
      check (letter_grade_scale is null or jsonb_typeof(letter_grade_scale) = 'array');
  end if;
end $$;

-- These tables are private to the Flask service. Browser clients authenticate
-- through NextAuth and never query Supabase directly.
alter table if exists public.semesters enable row level security;
alter table if exists public.courses enable row level security;
alter table if exists public.assignments enable row level security;
alter table if exists public.user_settings enable row level security;
alter table public.legacy_local_backups enable row level security;

do $$
begin
  if to_regclass('public.semesters') is not null then
    revoke all on table public.semesters from anon, authenticated;
  end if;
  if to_regclass('public.courses') is not null then
    revoke all on table public.courses from anon, authenticated;
  end if;
  if to_regclass('public.assignments') is not null then
    revoke all on table public.assignments from anon, authenticated;
  end if;
  if to_regclass('public.user_settings') is not null then
    revoke all on table public.user_settings from anon, authenticated;
  end if;
end $$;
revoke all on table public.legacy_local_backups from anon, authenticated;
